const data = {
  products: [
    {
      name: 'Pork',
      slug: 'pork',
      category: 'Meat',
      image: '/images/pork.jpg',
      rating: 4.5,
      price: 10,
      numReviews: 10,
      countInStock: 20,
      description: 'Delicious pork',
    },
    {
      name: 'Beef',
      slug: 'beef',
      category: 'Meat',
      image: '/images/beef.jpg',
      rating: 4,
      price: 20,
      numReviews: 5,
      countInStock: 25,
      description: 'Delicious beef',
    },
    {
      name: 'Sausage',
      slug: 'sausage',
      category: 'Food',
      image: '/images/sausage.jpg',
      rating: 3.5,
      price: 5,
      numReviews: 20,
      countInStock: 10,
      description: 'Delicious sausage',
    },
    {
      name: 'Pizza',
      slug: 'pizza',
      category: 'Food',
      image: '/images/pizza.jpg',
      rating: 4.0,
      price: 7,
      numReviews: 29,
      countInStock: 33,
      description: 'Delicious pizza',
    },
    {
      name: 'Pasta',
      slug: 'pasta',
      category: 'Food',
      image: '/images/pasta.jpg',
      rating: 4.5,
      price: 8,
      numReviews: 5,
      countInStock: 12,
      description: 'Delicious pasta',
    },
  ],
};
export default data;
